def load_coordinates():
    size_of_card = dict(
        width=75,
        height=55
    )

    dict_of_coords = dict(
        poker_table=dict(
            x=716,
            y=162,
            width=1190,
            height=850
        ),
        hand=dict(
            x=1240,
            y=705,
            width=150,
            height=55
        ),
        my_card_1=dict(
            x=1240,
            y=707,
            width=75,
            height=55
        ),
        my_card_2=dict(
            x=1315,
            y=707,
            width=75,
            height=55
        ),
        middle=dict(
            x=1115,
            y=463,
            width=400,
            height=110
        ),
        card_1=dict(
            x=1117,
            y=462,
            width=size_of_card['width'],
            height=size_of_card['height']
        ),
        card_2=dict(
            x=1197,
            y=462,
            width=size_of_card['width'],
            height=size_of_card['height']
        ),
        card_3=dict(
            x=1277,
            y=462,
            width=size_of_card['width'],
            height=size_of_card['height']
        ),
        card_4=dict(
            x=1355,
            y=462,
            width=size_of_card['width'],
            height=size_of_card['height']
        ),
        card_5=dict(
            x=1437,
            y=462,
            width=size_of_card['width'],
            height=size_of_card['height']
        )

    )
    return dict_of_coords
